name: Torque Environment Pipeline

on:
  workflow_dispatch:

jobs:
  Launch-stop-torque:
    runs-on: ubuntu-latest
    steps:
    - name: Start Torque Environment
      id: start-environment
      uses: QualiTorque/torque-start-environment@v1
      with:
        space: CandidateExercise-test	
        blueprint_name: ssm
        repository_name: qtorque
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        duration: 30
        timeout: 30

    - name: Delay for 6 minutes
      run: sleep 360

    - name: End Torque Environment
      uses: QualiTorque/torque-end-environment@v1
      with:
        space: CandidateExercise-test
        environment_id: ${{ steps.start-environment.outputs.environment_id }}
        torque_token: ${{ secrets.TORQUE_TOKEN }}
